project = 'CRAX Framework Documentation'
copyright = '2020, CRAX'
author = 'Eugene Mercousheu'
version = '0.0.7'
release = '0.0.7'
extensions = ['sphinx.ext.imgmath']
templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
language = 'en'
pygments_style = 'sphinx'
html_theme = 'crax_theme'
html_theme_path = ['_theme']
html_static_path = ['_theme/crax_theme']
html_show_sourcelink = False
